name: BTC Bot Every 5 Minutes

on:
  schedule:
    - cron: '*/5 * * * *'  # 每 5 分钟运行一次（UTC时间）
  workflow_dispatch:       # 支持手动运行（方便测试）

jobs:
  run-bot:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.11

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run BTC script
        env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          CHAT_ID: ${{ secrets.CHAT_ID }}
        run: python main.py
